### ISSUE TITLE
when I use  npm i nosql-leveldb，there some error

### ISSUE THREAD

**Issue by leochen-g** [snowyu/node-nosql-leveldb#5]
platform: Mac 10.12.5

```
> nosql-leveldb@3.0.1 install /Users/admin/project/wechatPad/node_modules/nosql-leveldb
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.1 runtime=node arch=x64 platform=darwin)
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/admin/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at Pipe._handle.close (net.js:600:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Users/admin/.nvm/versions/node/v10.15.1/bin/node" "/Users/admin/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/admin/project/wechatPad/node_modules/nosql-leveldb
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN wechatpad@1.0.0 No description
npm WARN wechatpad@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nosql-leveldb@3.0.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nosql-leveldb@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-03-08T06_29_02_066Z-debug.log
```

**Comment by snowyu** [comment]
It seems that the python vesion error. R u sure used the python2.7?

**Comment by mgttt** [comment]
leveldown.h:82:54: error: no matching function for call to ‘v8::Value::ToString

**Comment by snowyu** [comment]
@wanjochan report your used node, npm, python version. You should open a new issue.
